### ISSUE TITLE
Large (~512^3) cosmology simulations with Grackle failing at cycle 0

### ISSUE THREAD

**Issue by WillHicks96** [enzo-project/enzo-e#260]
I ran into this when trying to start a 512^3 simulation on 256 nodes on Frontera with nine-species chemistry out of the current version of `main`. I've recently run smaller simulations (e.g. 128^3) with the same setup without any issues, so it's only happening on larger sims.

The error output suggests that some of the rates being passed into Grackle in `initialize_grackle_chemistry_data` are NaNs. This is somehow related to PR #173. To confirm this, I undid the changes to the relevant files that PR #173 made, and the simulation started without any issues. It did eventually fail with a negative energy error in PPM after ~500 cycles, although I'm not sure if this is a separate issue or if I just screwed something up when undoing the changes in PR #173 (I saved this branch here: https://github.com/WillHicks96/enzo-e/tree/old_grackle).

Full output from the sim: [N512_stdout.txt](https://github.com/enzo-project/enzo-e/files/9135591/N512_stdout.txt)
`parameters.out` file (renamed parameters.txt so I can attach it): [parameters.txt](https://github.com/enzo-project/enzo-e/files/9135588/parameters.txt)
MUSIC parameter file for generating ICs: [N512_CSA.txt](https://github.com/enzo-project/enzo-e/files/9135606/N512_CSA.txt)

**Comment by mabruzzo** [comment]
Sorry it took me so long to get to this, I've started working on this, but If you still have them, would you mind providing me with the versions of the parameter file for the 128^3 run (or at least edit provide a version of the MUSIC parameter file to generate appropriate ICs...)?

**Comment by mabruzzo** [comment]
Sorry for taking so long to address this. This was a rather tricky issue to debug

I _think_ that the issue was that we weren't PUPing the `chemistry_data` struct's `dust_recombination_cooling` and `H2_custom_shielding` fields. Presumably some other differences between the branches caused those parameters to get initialized to different junk values when the parameters got communicated between nodes.

I'm currently running some tests to verify my conclusion, but initial results are promising! (Things no longer crashing)! I'll have an update for you about this later today.

As an aside, I have plans to introduce a PR to completely avoid this class of bugs (in the PUP routine) in the future. It will make use of new functions that I wrote for Grackle (they actually just got merged into Grackle this morning)

**Comment by mabruzzo** [comment]
Following up, I confirmed that after adding the missing pup commands:
- Will's branch where he reverted grackle
- to the main branch at commit 07711890e246a5e0d8c85755991aca06ba1a5911

the two different branches produce the same output. For posterity, I compared the outputs with a variant of [this script](https://pastebin.com/rynfXSL8).
