### ISSUE TITLE
Ambiguous meaning of "mass"

### ISSUE THREAD

**Issue by jobordner** [enzo-project/enzo-e#54]
[This issue is in response to a review comment by @aemerick in #12.]

In EnzoMethodPmDeposit, the "dark" particle's mass is interpreted differently depending on whether cosmology is enabled:

`     // Required for Cosmology ("mass" is mass)`                                                                       
`      // Not for Collapse ("mass" is density)`                                                                             
`      if (cosmology) {`
`        dens *= std::pow(2.0,rank*level);`
`      }`

This confusion needs to be clarified.  Also, "dark" particles should not be hard-coded into the method.

**Comment by stefanarridge** [comment]
Is there a good reason why we would want particles to carry a 'density' attribute rather than 'mass'? If this is necessary then my suggestion would be for the attribute to be called 'density', and then put particles with this attribute in a 'has_density' group?

In any case, why does the above code snippet check for whether cosmology is enabled? It seems to be adjusting the density for the refinement level, but why would you only do this for a cosmological simulation? 

It is worth noting that for star and sink particles, the particle mass is required for physics other than the gravity such as feedback and accretion, so clearing up this issue would help in that regard as well.
